config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :players, only: %i[show new create]
  resources :games, param: :token, only: %i[show create]
  resources :estimates, only: [:create]
  resources :point_statuses, only: [:create]

  root 'games#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/estimate.rb
# frozen_string_literal: true

class Estimate < ApplicationRecord
  belongs_to :player

  def self.save_and_broadcast(player_id, point)
    estimate = Estimate.find_or_initialize_by(player_id:)
    estimate.point = point
    estimate.save!

    estimate.broadcast_update_to estimate.player.game, target: "#{estimate.player_id}_estimate"
  end
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_one :point_status, dependent: :destroy

  before_validation :set_token, on: :create

  validates :token, presence: true, uniqueness: true

  def to_param
    token
  end

  private

  def set_token
    self.token = SecureRandom.urlsafe_base64(16)
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :game
  has_many :estimates, dependent: :destroy
end

app/models/point_status.rb
# frozen_string_literal: true

class PointStatus < ApplicationRecord
  belongs_to :game

  def status_class
    case status
    when 0
      'hide_point'
    when 1
      'open_point'
    end
  end

  broadcasts_to :game
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/estimates_controller.rb
# frozen_string_literal: true

class EstimatesController < ApplicationController
  def create
    Estimate.save_and_broadcast(session[:player_id], params_estimate[:point])
  end

  private

  def params_estimate
    params.require(:estimate).permit(:point)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show]

  # GET /games/1 or /games/1.json
  def show
    @player = @game.players.find_or_initialize_by(id: session[:player_id])
    @players = @game.players
    @point_status = @game.point_status || PointStatus.new(game: @game)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_game
    @game = Game.find_by(token: params[:token])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[show]

  # GET /players/1 or /players/1.json
  def show
    @players = @player.game.players
    @point_status = @player.game.point_status || PointStatus.new(game: @player.game)
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        session[:player_id] = @player.id
        @player.broadcast_append_to @player.game
        format.html { redirect_to player_url(@player) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:name, :game_id)
  end
end

app/controllers/point_statuses_controller.rb
# frozen_string_literal: true

class PointStatusesController < ApplicationController
  def create
    player = Player.find_by(id: session[:player_id])
    game = player.game
    point_status = game.point_status || PointStatus.new(game:)
    point_status.status = point_status_params[:status].to_i
    point_status.broadcast_replace_to game, target: 'point_status' if point_status.save!
  end

  private

  def point_status_params
    params.require(:point_status).permit(:status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/helpers/point_statuses_helper.rb
# frozen_string_literal: true

module PointStatusesHelper
end

app/views/estimates/_estimate.html.erb
<%= estimate.point %>

app/views/estimates/_form.html.erb
<div class="estimate_buttons">
  <% %w(1 2 3 5 8 13 21 34 55).each do |n| %>
    <%= form_with(url: estimates_url, scope: :estimate) do |f| %>
      <%= f.hidden_field :point,  value: n %>
      <%= f.submit(n) %>
    <% end %>
  <% end %>
</div>

app/views/games/_field.html.erb
<%= turbo_stream_from player.game %>
<%= render partial: "estimates/form" %>
<%= render partial: "point_statuses/form", locals: {point_status: point_status} %>
<%= render partial: "players/index", locals: {myself: myself, players: players, point_status: point_status} %>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Game:</strong>
    <%= game.name %>
  </p>
</div>
<% if @player.new_record? %>
  <%= turbo_frame_tag 'player_new' do %>
    <%= render partial: "players/form", locals: {player: @player} %>
  <% end %>
<% else %>
  <%= render partial: "games/field", locals: {myself:@player, player: @player, players: @players, point_status: @point_status} %>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/new.html.erb
<h1>Create New game</h1>

<%= render "form", game: @game %>

app/views/games/show.html.erb
<%= render @game %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <%= form.hidden_field :game_id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_index.html.erb
<div data-controller="reset" data-reset-property-value="innerHTML" data-reset-reset-value="">
  <%= render point_status %>
  <div id="players">
    <% players.each do |player| %>
      <%= content_tag :div, class: { myself: myself.id == player.id } do %>
        <%= render player %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/players/_player.html.erb
<div class="player">
  <div id="<%= dom_id player %>" class="player_name">
    <%= player.name %>
  </div>
  <div class="point_area">
    <div id="<%= "#{player.id}_estimate" %>" class="point" data-reset-target="point">
      <%= player.estimates&.first&.point %>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<%= turbo_frame_tag 'player_new' do %>
  <%= render partial: "games/field", locals: {myself: @player, player: @player, players: @players, point_status: @point_status} %>
<%end%>

app/views/point_statuses/_form.html.erb
<div class="game_buttons">
  <%= form_with(url: point_statuses_url, model: point_status, method: :post ) do |f| %>
    <%= f.hidden_field :status, value: '1' %>
    <%= f.submit 'open' %>
  <% end %>
  <%= form_with(url: point_statuses_url, model: point_status, method: :post ) do |f| %>
    <%= f.hidden_field :status, value: '0' %>
    <%= f.submit 'reset' %>
  <% end %>
</div>

app/views/point_statuses/_point_status.html.erb
<div id="point_status" data-reset-target="pointStatus" class="<%= point_status.status_class %>"></div>